Align styles with current brand
HedvigInsurance/gatekeeper pull request #16
Opened 2021-03-06 16:41 UTC by rasmusguterstam

A long time coming on this one: get rid of the double sign-in, and align the OAuth Gatekeeper prompt to current brand 💅

https://github.com/HedvigInsurance/hedgehog/pull/288

2021-03-06 17:31 UTC, vonElfvin approved these changes
😮

2021-03-08 08:36 UTC, palmenhq requested changes
Great stuff! However shall we update the other templates also?

Or - even better - refactor a bit. Feels like the templates have a lot of duplicate code. Maybe we could utilise [template extensions](https://pebbletemplates.io/wiki/tag/extends/)?

2021-03-15 14:19 UTC, palmenhq submitted a review, later dismissed
Good stuff!

2021-03-15 14:19 UTC, palmenhq commented on src/main/resources/templates/sso/base.html.peb
> +</script>
what about placing the script tags inside the block in the extensions? That way i think it's easier to know what to put here.

2021-03-18 13:20 UTC, palmenhq approved these changes

2021-03-18 13:40 UTC, merged